// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: base/segment.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcBizToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizType string `protobuf:"bytes,1,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *GrpcBizToken) Reset() {
	*x = GrpcBizToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcBizToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcBizToken) ProtoMessage() {}

func (x *GrpcBizToken) ProtoReflect() protoreflect.Message {
	mi := &file_base_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcBizToken.ProtoReflect.Descriptor instead.
func (*GrpcBizToken) Descriptor() ([]byte, []int) {
	return file_base_segment_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcBizToken) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *GrpcBizToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GrpcSegmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizType   string `protobuf:"bytes,1,opt,name=BizType,proto3" json:"BizType,omitempty"`
	StartId   int64  `protobuf:"varint,2,opt,name=StartId,proto3" json:"StartId,omitempty"`
	Step      int64  `protobuf:"varint,3,opt,name=Step,proto3" json:"Step,omitempty"`
	Incr      int64  `protobuf:"varint,4,opt,name=Incr,proto3" json:"Incr,omitempty"`
	Remainder int64  `protobuf:"varint,5,opt,name=Remainder,proto3" json:"Remainder,omitempty"`
}

func (x *GrpcSegmentInfo) Reset() {
	*x = GrpcSegmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_segment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcSegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSegmentInfo) ProtoMessage() {}

func (x *GrpcSegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_base_segment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSegmentInfo.ProtoReflect.Descriptor instead.
func (*GrpcSegmentInfo) Descriptor() ([]byte, []int) {
	return file_base_segment_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcSegmentInfo) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *GrpcSegmentInfo) GetStartId() int64 {
	if x != nil {
		return x.StartId
	}
	return 0
}

func (x *GrpcSegmentInfo) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *GrpcSegmentInfo) GetIncr() int64 {
	if x != nil {
		return x.Incr
	}
	return 0
}

func (x *GrpcSegmentInfo) GetRemainder() int64 {
	if x != nil {
		return x.Remainder
	}
	return 0
}

var File_base_segment_proto protoreflect.FileDescriptor

var file_base_segment_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x47, 0x72,
	0x70, 0x63, 0x42, 0x69, 0x7a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x69,
	0x7a, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x69, 0x7a,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x47,
	0x72, 0x70, 0x63, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x63, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x49, 0x6e, 0x63, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x52,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x32, 0x46, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x42, 0x69, 0x7a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x15, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x3b, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_segment_proto_rawDescOnce sync.Once
	file_base_segment_proto_rawDescData = file_base_segment_proto_rawDesc
)

func file_base_segment_proto_rawDescGZIP() []byte {
	file_base_segment_proto_rawDescOnce.Do(func() {
		file_base_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_segment_proto_rawDescData)
	})
	return file_base_segment_proto_rawDescData
}

var file_base_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_segment_proto_goTypes = []interface{}{
	(*GrpcBizToken)(nil),    // 0: base.GrpcBizToken
	(*GrpcSegmentInfo)(nil), // 1: base.GrpcSegmentInfo
}
var file_base_segment_proto_depIdxs = []int32{
	0, // 0: base.GrpcSegment.GetSegment:input_type -> base.GrpcBizToken
	1, // 1: base.GrpcSegment.GetSegment:output_type -> base.GrpcSegmentInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_segment_proto_init() }
func file_base_segment_proto_init() {
	if File_base_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcBizToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_segment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcSegmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_segment_proto_goTypes,
		DependencyIndexes: file_base_segment_proto_depIdxs,
		MessageInfos:      file_base_segment_proto_msgTypes,
	}.Build()
	File_base_segment_proto = out.File
	file_base_segment_proto_rawDesc = nil
	file_base_segment_proto_goTypes = nil
	file_base_segment_proto_depIdxs = nil
}
